language: python
dist: bionic
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - os: osx
      language: generic
      python: ""
addons:
  apt:
    packages:
      - pandoc
      - ffmpeg
  homebrew:
    packages:
      - pandoc
      - ffmpeg
install:
  - python3 --version
  - python3 -m pip --version
  - python3 -m pip install .
  - python3 -m pip install -r tests/requirements.txt
  - python3 -m pip install -r doc/requirements.txt
  # This is needed in example scripts:
  - python3 -m pip install pillow
script:
  - python3 -m pytest
  - python3 doc/examples/run_all.py
  # This executes the example notebooks and runs the doctests:
  - python3 -m sphinx doc/ _build/ -b doctest -W
